# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Mission"
  pageRef = "https://hello.com"
  weight = 10

[[main]]
  name = "About"
  parent = "Mission"
  url = "#bio"
  weight = 10

[[main]]
  name = "Success Stories"
  parent = "Mission"
  url = "#testimonials"
  weight = 20

[[main]]
  name = "Failures and Learnings"
  parent = "Mission"
  pageRef = "/about/failures"
  weight = 30

[[main]]
  name = "Courses"
  pageRef = "https://example.com"
  weight = 20

[[main]]
  name = "Course Connection"
  parent = "Courses"
  url = "#courses"
  weight = 20

[[main]]
  name = "Course Practice"
  parent = "Courses"
  url = "#practice"
  weight = 20

[[main]]
  name = "Events"
  pageRef = "/events"
  weight = 30

[[main]]
  name = "Upcoming Events"
  parent = "Events"
  url = "#practice"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "https://demodeveloperlab.github.io/innerknowing/en/#recent-posts/"
  weight = 40

[[main]]
  name = "Posts"
  parent = "Publications"
  url = "https://demodeveloperlab.github.io/innerknowing/en/posts/"
  weight = 10

[[main]]
  name = "Books"
  parent = "Publications"
  url = "#books"
  weight = 20

[[main]]
  name = "Sources"
  pageRef = "https://example.com"
  weight = 50

[[main]]
  name = "Reading"
  parent = "Sources"
  pageRef = "/sources/reading"
  weight = 10

[[main]]
  name = "Links"
  parent = "Sources"
  pageRef = "/sources/links"
  weight = 20

[[main]]
  name = "Sitemap"
  parent = "Sources"
  pageRef = "https://example.com"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "https://example.com"
  weight = 60

[[main]]
  name = "Contact Form"
  parent = "Contact"
  url = "#message"
  weight = 10

[[main]]
  name = "Inner Group"
  parent = "Contact"
  pageRef = "events/inner-group"
  weight = 20

[[main]]
  name = "Contact"
  parent = "Contact"
  pageRef = "posts"
  weight = 30

[[main]]
  title = "twitter"
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/burufugu"
  weight = 200

[[main]]
  title = "mastodon"
  identifier = "mastodon"
  pre = "mastodon"
  url = "https://masto.ai/@blowfish"
  weight = 300

[[main]]
  title = "github"
  identifier = "github"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 400

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "üóÇÔ∏è Series"
  pageRef = "series"
  weight = 10

[[footer]]
  name = "üìÅ Categories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "üè∑Ô∏è Tags"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "üë• Authors"
  pageRef = "authors"
  weight = 40